"""
Data parser and ingestion interface for TIDAL algorithmic mixes.

Converts artifacts from tidal-algorithmic-mixes (SASRec top-6000 pools,
PySpark Daily Discovery transformations, and user interaction histories)
into structured PyTorch dataclasses with synthetic fallback mechanisms.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional, Union
import json
import numpy as np
import pandas as pd
import pyarrow.parquet as pq


@dataclass
class UserInteractionSequence:
    """Historical interaction trajectory for an individual listener."""
    user_id: int
    track_ids: List[int]
    durations_ms: List[int]
    skip_flags: List[bool]
    context_taxes: List[float] = field(default_factory=list)


@dataclass
class TrackCandidatePool:
    """Candidate track pool emitted by the SASRec candidate generation stage."""
    track_ids: np.ndarray
    artist_ids: np.ndarray
    cluster_ids: np.ndarray
    embeddings: np.ndarray          # Shape: (M, D) on S^(D-1)
    is_mainstream: np.ndarray       # Shape: (M,) boolean
    subgenre_labels: List[str]


@dataclass
class SubgenreMetadata:
    """Cluster mappings for localised subgenres and commercial baselines."""
    cluster_to_subgenre: Dict[int, str]
    subgenre_names: List[str]


class TidalLogParser:
    """
    Ingests and validates recommendation candidate slates and interaction logs
    conforming to TIDAL's open-source pipeline schemas.
    """

    SUBGENRES = ["Amapiano", "Gqom", "Lekompo", "Bacardi"]

    def __init__(self, seed: Optional[int] = 42) -> None:
        self.rng = np.random.default_rng(seed)

    def parse_parquet_candidates(self, parquet_path: Union[str, Path]) -> TrackCandidatePool:
        """
        Parses Parquet output generated by TIDAL's PySpark Daily Discovery transformations.
        """
        path = Path(parquet_path)
        if not path.exists():
            raise FileNotFoundError(f"Parquet candidate file not found at: {path}")

        table = pq.read_table(path)
        df = table.to_pandas()

        required_cols = {"track_id", "artist_id", "cluster"}
        if not required_cols.issubset(df.columns):
            raise ValueError(f"Parquet missing required TIDAL columns: {required_cols - set(df.columns)}")

        track_ids = df["track_id"].values.astype(np.int64)
        artist_ids = df["artist_id"].values.astype(np.int64)
        cluster_ids = df["cluster"].values.astype(np.int64)

        num_tracks = len(track_ids)
        if "embedding" in df.columns:
            embeddings = np.stack(df["embedding"].values).astype(np.float32)
            # Project onto unit hypersphere with epsilon inside square root
            norms = np.sqrt(np.sum(embeddings ** 2, axis=1, keepdims=True) + 1e-7)
            embeddings = embeddings / norms
        else:
            embeddings = self._generate_hypersphere_embeddings(num_tracks, dim=64)

        if "is_mainstream" in df.columns:
            is_mainstream = df["is_mainstream"].values.astype(bool)
        else:
            is_mainstream = (self.rng.uniform(0.0, 1.0, size=num_tracks) < 0.25)

        subgenre_labels = [self.SUBGENRES[c % len(self.SUBGENRES)] for c in cluster_ids]

        return TrackCandidatePool(
            track_ids=track_ids,
            artist_ids=artist_ids,
            cluster_ids=cluster_ids,
            embeddings=embeddings,
            is_mainstream=is_mainstream,
            subgenre_labels=subgenre_labels,
        )

    def parse_json_logs(self, json_path: Union[str, Path]) -> List[UserInteractionSequence]:
        """Parses JSON-serialized sequence logs matching TIDAL's user interaction format."""
        path = Path(json_path)
        if not path.exists():
            raise FileNotFoundError(f"JSON interaction logs not found at: {path}")

        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)

        sequences = []
        for record in data:
            sequences.append(
                UserInteractionSequence(
                    user_id=int(record["user_id"]),
                    track_ids=list(record["track_ids"]),
                    durations_ms=list(record.get("durations_ms", [180_000] * len(record["track_ids"]))),
                    skip_flags=list(record.get("skip_flags", [False] * len(record["track_ids"]))),
                    context_taxes=list(record.get("context_taxes", [0.0] * len(record["track_ids"]))),
                )
            )
        return sequences

    def _generate_hypersphere_embeddings(self, count: int, dim: int = 64) -> np.ndarray:
        """
        Generates vectors strictly bounded on S^(D-1).
        Numerical constraint: epsilon placed inside square root.
        """
        raw = self.rng.standard_normal((count, dim)).astype(np.float32)
        norms = np.sqrt(np.sum(raw ** 2, axis=-1, keepdims=True) + 1e-7)
        return raw / norms

    def synthesize_candidate_pool(
        self,
        pool_size: int = 6000,
        dim: int = 64,
        num_subgenres: int = 4,
    ) -> TrackCandidatePool:
        """
        High-throughput synthetic fallback generating a compliant TIDAL candidate pool.
        Matches the 6,000 candidate output emitted by TIDAL's SASRec backbone.
        """
        track_ids = np.arange(1, pool_size + 1, dtype=np.int64)
        
        # Artist distribution: Pareto/Zipf-like artist popularities
        num_artists = pool_size // 4
        artist_weights = 1.0 / (np.arange(1, num_artists + 1) ** 0.8)
        artist_weights /= artist_weights.sum()
        artist_ids = self.rng.choice(np.arange(1, num_artists + 1), size=pool_size, p=artist_weights)

        # Cluster IDs mapped across subgenres
        cluster_ids = self.rng.integers(0, num_subgenres, size=pool_size, dtype=np.int64)

        # Mainstream flags (top 20% most frequent artists flagged as mainstream)
        unique_artists, counts = np.unique(artist_ids, return_counts=True)
        top_artist_cutoff = np.percentile(counts, 80)
        mainstream_artists = set(unique_artists[counts >= top_artist_cutoff])
        is_mainstream = np.array([a in mainstream_artists for a in artist_ids], dtype=bool)

        embeddings = self._generate_hypersphere_embeddings(pool_size, dim=dim)
        subgenre_labels = [self.SUBGENRES[c % len(self.SUBGENRES)] for c in cluster_ids]

        return TrackCandidatePool(
            track_ids=track_ids,
            artist_ids=artist_ids,
            cluster_ids=cluster_ids,
            embeddings=embeddings,
            is_mainstream=is_mainstream,
            subgenre_labels=subgenre_labels,
        )

    def synthesize_interaction_trajectories(
        self,
        num_users: int = 128,
        trajectory_length: int = 30,
        slate_size: int = 10,
        pool_size: int = 6000,
    ) -> List[Dict[str, np.ndarray]]:
        """
        Synthesizes multi-step user-slate interaction trajectories for offline RSSM training.

        Returns a list of dictionaries with action slates, stream feedbacks, and Context Taxes.
        """
        trajectories = []
        for u in range(num_users):
            actions = self.rng.integers(0, pool_size, size=(trajectory_length, slate_size), dtype=np.int64)
            # Simulated consumption: items in user's preferred cluster stream more
            preferred_cluster = u % len(self.SUBGENRES)
            
            # Synthetic feedback matrices
            streams = self.rng.binomial(1, p=0.45, size=(trajectory_length, slate_size)).astype(np.float32)
            context_taxes = self.rng.normal(loc=0.25, scale=0.15, size=(trajectory_length, 1)).astype(np.float32)
            context_taxes = np.clip(context_taxes, -1.0, 1.0)

            trajectories.append({
                "user_id": np.array([u], dtype=np.int64),
                "actions": actions,
                "streams": streams,
                "context_taxes": context_taxes,
            })
        return trajectories
